### ISSUE TITLE
Multiple Library locations / folders

### ISSUE THREAD

**Issue by nstarke** [ChrisTheCoolHut/Firmware_Slap#19]
Is it possible to specify multiple LD_PATH / library locations (`-L`) for `Discover_and_Dump.py` ?  If not, could you give me a brief rundown on where you would put that functionality so I can create a pull request to add this feature?  Thank you!

**Comment by ChrisTheCoolHut** [comment]
In `firmware_slap/function_analyzer.py` the `do_trace` function accepts a string for ld_path. on line [200](https://github.com/ChrisTheCoolHut/Firmware_Slap/blob/5c5d2d1cdf554aef3fbe58e0fc6b69d8e9f716eb/firmware_slap/function_analyzer.py#L200) it is passed as a string to `angr.Project()`.

Behind the scenes it is checking to see if this object is a string or a list. You can pass `ld_path` here a list of paths to check instead of a string. So if you modify `ld_path` in function_analyzer (do_trace & trace_function) (and all dependents) to use a list instead you can have it specify multiple paths.

I would likely just turn args.ld_path into a list by splitting on `:` like ld-linux does, so the style is similar.

eg: `-L /sysroot/lib:/sysroot/usr/lib`

**Comment by nstarke** [comment]
I'll attempt to submit a PR tonight.  Thanks!
